apiVersion: v1
kind: Service
metadata:
  name: qdrant
  namespace: {{ .Values.namespace }}
spec:
#  clusterIP: None  # Headless service for StatefulSet? -- not needed yet
  selector:
    app: qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
    - name: grpc
      port: 6334
      targetPort: 6334